version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${BH_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${BH_DATABASE_PASSWORD}
    env_file: .env
  reverse-proxy-nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./public/flutter:/usr/share/nginx/html
    depends_on:
      - server
  server:
    build: 
      context: .
      dockerfile: dcb.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RAILS_MASTER_KEY=${PRODUCTION_SECRET_KEY}
      - RAILS_ENV=production
    env_file: .env